title: Moria AI Lab - Data Readiness Engine 
description: Beyond Data Readiness - The Moria AI Lab's Engine for Data-Driven Decision Making
theme: minima

author:
  name: Hugo Contreras-Palacios
  email: hugocontrerasp@gmail.com

social_links:
  - title: Minima Theme repository at GitHub
    icon: github
    url: "https://github.com/jekyll/minima"
  - title: Jekyll at X (formerly Twitter)
    icon: x-twitter
    url: "https://x.com/jekyllrb"

