title: Moria AI Lab - Data Readiness Engine 
description: Beyond Data Quality - Data Readiness for AI
theme: minima

author:
  name: Hugo Contreras, PhD
  email: hugocontrerasp@gmail.com
minima:
  social_links:
    - title: Minima Theme repository at GitHub
      icon: github
      url: "https://github.com/jekyll/minima"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"

